import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, header, footer
}: {
  children: React.ReactNode
  header: React.ReactNode
  footer: React.ReactNode

}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <header>{header}</header>
        <main>{children}</main>
        <footer>{footer}</footer>
      </body>
    </html>
  )
}
